using Symbolics

@variables cp, k, rho, mu, g, D_p, L, epsilon #physical parameters (with units)

@variables a b c d e #empirical variables like 1.75 in ergun equations

#I wonder if better guesses could be generated by a machine learning algorithim that is trained off of already existing empirical correlations and physics expressions
#perhaps units could also aid in this process if we're not going completely empirical
#I think we could achieve this by modelling expressions as trees and then have a model that's given the input: 
    #- output units
    #- output magnitude
    #- independent variable magnitude
    #- avaliable physical parameters (like specific heat capacity, density, reynolds number, prandtl number, )
    #- etc.
#and outputs:
    #- probable next operation
    #- probable next coefficient
    #- probable next occurance of an independent variable
    #- probable next occurance of a physical parameters
    #- units of next coefficient
    #- etc.

#this training could even be reinforced by feeding back in the equations that were the simplest that also resulted in the best fit

#if we could pull this off, we could have a model that could automatically generate simple-looking empirical correlations that would typically 
#take years to create with very simple hardware which would be insanely valuable
#god I love Julia

#I think a good way to test this would be to see if it could come up with the reynolds number formula by fitting it to data generated from the original formula

#I wonder if developing such a thing would even be worth it

#I mean, on the two ends of the spectrum you would either have simulations that run so fast that just throwing shit at a wall randomly will eventually work,
#or when simulation times are so high 

operators = [+, -, *, ^, /, log, ⋅] #exp and sqrt doesn't work here
#- we would probably want a lower chance of getting rare operators like log, dot, sqrt, sin, cos, tan, etc.
physical_parameters = [cp, k, rho, mu, g, D_p, L, epsilon]
empirical_constants = [a, b, c, d, e]

# 3. Simple generator function
function generate_random_expr(depth)
    test_rand = rand()
    println(test_rand)
    if depth <= 0 #|| test_rand < 0.3 
        # Return a variable or constant
        return rand([physical_parameters...; empirical_constants...])
    else
        # Return a random operation applied to recursive calls
        op = rand(operators)
        return op(generate_random_expr(depth-1), generate_random_expr(depth-1))
    end
end

# Generate a random expression of max depth 3
random_1st_order_exprs = [generate_random_expr(1)]

random_expr = generate_random_expr(3)
println(random_expr)
# Example output: (x * y) - (x + 5)