//Note: this code was generated by Gemini 3.1 Pro and slightly modified by me
//I have tested this code and it works
//While I generally don't like using AI to generate code, I don't know C++, 
//so this seemed like the only option to at least get something working

#include <SPI.h>
#include <Adafruit_MAX31855.h>

// --- THERMOCOUPLE SETUP ---
#define CS1 2
#define CS2 3
#define CS3 4
#define CS4 5
#define CS5 6

Adafruit_MAX31855 tc1(CS1);
Adafruit_MAX31855 tc2(CS2);
Adafruit_MAX31855 tc3(CS3);
Adafruit_MAX31855 tc4(CS4);
Adafruit_MAX31855 tc5(CS5);

Adafruit_MAX31855* thermocouples[] = {&tc1, &tc2, &tc3, &tc4, &tc5};
const int numSensors = 5;

// Variables for non-blocking temperature reads
unsigned long previousTempMillis = 0;
const long tempInterval = 500; // Read temperatures every 1000 milliseconds

// --- STEPPER MOTOR SETUP ---
// MOVED PINS to avoid Hardware SPI conflicts!
#define DIR_PIN 7 
#define ENA_PIN 8 
#define PUL_PIN 9 

// Variables for non-blocking stepper pulses
unsigned long previousStepMicros = 0;

// To achieve very low flow with 6400 pulses/rev:
// E.g., 1 RPM = 6400 pulses per 60 seconds = ~106 pulses/second.
// 1 second (1,000,000 micros) / 106 = ~9433 microseconds between pulses.
// Change this value to adjust your flow rate. Higher number = slower flow.
double target_rpm = 5.0; //change me!

long pulses_per_revolution = 6400; //check TB6600 for the pulse/rev, the setting resulting in the highest pulse/rev should be used
double pulses_per_second = target_rpm * pulses_per_revolution / 60;
unsigned long stepIntervalMicros = 1_000_000 / pulses_per_second;

// Motor direction state
bool motorDirection = true; // true for one way, false for the other

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(1);

  // Initialize Stepper Pins
  pinMode(PUL_PIN, OUTPUT);
  pinMode(DIR_PIN, OUTPUT);
  pinMode(ENA_PIN, OUTPUT);

  // Common Anode Logic Setup
  digitalWrite(PUL_PIN, HIGH); // Default state HIGH (no pulse)
  digitalWrite(ENA_PIN, HIGH); // HIGH means NO current flows, which KEEPS DRIVER ENABLED
  
  // Set initial direction
  if(motorDirection) {
    digitalWrite(DIR_PIN, LOW); 
  } else {
    digitalWrite(DIR_PIN, HIGH);
  }

  // Initialize all sensors
  for (int i = 0; i < numSensors; i++) {
    if (!thermocouples[i]->begin()) {
      Serial.print("Error initializing Thermocouple ");
      Serial.println(i + 1);
      while (1) delay(10); 
    }
  }

  Serial.println("Time_ms,TC1_C,TC2_C,TC3_C,TC4_C,TC5_C");
  delay(500); // Give MAX31855 time to stabilize initially
}

void loop() {
  unsigned long currentMillis = millis();
  unsigned long currentMicros = micros();

  // ---------------------------------------------------------
  // 1. NON-BLOCKING STEPPER MOTOR CONTROL
  // ---------------------------------------------------------
  if (currentMicros - previousStepMicros >= stepIntervalMicros) {
    // Save the last time we pulsed the motor
    previousStepMicros = currentMicros;

    // Common anode logic: pulling LOW turns the internal LED ON, registering a pulse
    digitalWrite(PUL_PIN, LOW); 
    
    // The TB6600 needs a minimum pulse width of a few microseconds to register
    delayMicroseconds(50); 
    
    digitalWrite(PUL_PIN, HIGH); // Return to HIGH to end the pulse
  }

  // ---------------------------------------------------------
  // 2. NON-BLOCKING TEMPERATURE READINGS
  // ---------------------------------------------------------
  if (currentMillis - previousTempMillis >= tempInterval) {
    // Save the last time we read temperatures
    previousTempMillis = currentMillis;

    Serial.print(currentMillis);
    Serial.print(",");

    for (int i = 0; i < numSensors; i++) {
      double temp = thermocouples[i]->readCelsius();
      
      // --- ADDED RETRY LOGIC ---
      byte retries = 0;
      while (isnan(temp) && retries < 3) {
        smartDelay(50); // Wait 5ms for electrical noise to clear
        temp = thermocouples[i]->readCelsius();
        retries++;
      }
      // -------------------------

      if (isnan(temp)) {
        Serial.print("NaN"); // If it still fails after 3 retries, print NaN
      } else {
        Serial.print(temp);
      }

      if (i < numSensors - 1) {
        Serial.print(",");
      }
    }
    Serial.println();
  }
}

void smartDelay(unsigned long waitMillis) {
  unsigned long startWait = millis();
  
  while (millis() - startWait < waitMillis) {
    unsigned long currentMicros = micros();
    
    // Check if the stepper motor needs a pulse during the wait time
    if (currentMicros - previousStepMicros >= stepIntervalMicros) {
      previousStepMicros = currentMicros;
      digitalWrite(PUL_PIN, LOW); 
      delayMicroseconds(50); 
      digitalWrite(PUL_PIN, HIGH); 
    }
  }
}