//Note: this code was generated by Gemini 3.1 Pro and slightly modified by me
//I have tested this code and it works
//While I generally don't like using AI to generate code, I don't know C++, so this seemed like the only option to at least get something working

#include <SPI.h>
#include <Adafruit_MAX31855.h>

// Define the unique Chip Select (CS) pins for each thermocouple
#define CS1 2
#define CS2 3
#define CS3 4
#define CS4 5
#define CS5 6

// Initialize the 5 sensor objects using Hardware SPI
Adafruit_MAX31855 tc1(CS1);
Adafruit_MAX31855 tc2(CS2);
Adafruit_MAX31855 tc3(CS3);
Adafruit_MAX31855 tc4(CS4);
Adafruit_MAX31855 tc5(CS5);

// Create an array of pointers to the sensors to make looping easy
Adafruit_MAX31855* thermocouples[] = {&tc1, &tc2, &tc3, &tc4, &tc5};
const int numSensors = 5;

void setup() {
  // Start serial communication at a fast baud rate
  Serial.begin(115200);
  
  // Wait for the serial connection to establish
  while (!Serial) delay(1);

  // Initialize all sensors
  for (int i = 0; i < numSensors; i++) {
    if (!thermocouples[i]->begin()) {
      Serial.print("Error initializing Thermocouple ");
      Serial.println(i + 1);
      // Wait forever if there's an error
      while (1) delay(10); 
    }
  }

  // Print CSV Header
  Serial.println("Time_ms,TC1_C,TC2_C,TC3_C,TC4_C,TC5_C");
  
  // The MAX31855 needs time to stabilize its first reading
  delay(500); 
}

void loop() {
  // Print current time in milliseconds
  Serial.print(millis());
  Serial.print(",");

  // Read and print each thermocouple
  for (int i = 0; i < numSensors; i++) {
    double temp = thermocouples[i]->readCelsius();
    
    if (isnan(temp)) {
      // If there's an error reading the sensor, print a designated error value
      Serial.print("NaN");
    } else {
      Serial.print(temp);
    }

    // Add a comma after all but the last reading
    if (i < numSensors - 1) {
      Serial.print(",");
    }
  }
  
  // Print a newline at the end of the data row
  Serial.println();

  // Wait 1 second before the next reading. 
  // Note: The MAX31855 requires at least ~250ms between reads.
  delay(1000); 
}